### ISSUE TITLE
Vue Property for SVG Maps for icons and labels

### ISSUE THREAD

**Issue by phucmp** [VictorCazanave/vue-svg-map#16]
I am trying to add span text onto the individual states to indicate States and potentially number of cities. Do you know if there is an easy way to do this?

**Comment by VictorCazanave** [comment]
Hi @phucmp,
Sorry for the late reply, I missed the notification 🙇‍♂️ 

A solution (that I haven't tried) may be to use the [slots](https://github.com/VictorCazanave/vue-svg-map#slots) of `SvgMap` component to insert [`<text>` elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) at the right position.

**Comment by VictorCazanave** [comment]
@phucmp feel free to re-open this issue if you have more questions.
