### ISSUE TITLE
There is no computed style property for the map

### ISSUE THREAD

**Issue by juan-carvajal** [VictorCazanave/vue-svg-map#22]
Even if the map includes the property to select custom classes for each location, there is no feasible way to computed the color based on input data. Take for example a heat map, lets say each country has some datapoint, and will be colored acording to this datapoint, is not possible to generate a class for each country, there must be a computed style, not class.

**Comment by VictorCazanave** [comment]
Hello @juan-carvajal,
Is it a question or a feature request?

**Comment by juan-carvajal** [comment]
It could be both, it is a question if the feature is present and I am somehow missing it, othewise is a feature requeste pleaseeee. Thanks btw

**Comment by VictorCazanave** [comment]
Actually it's possible to add custom HTML attributes to each `<path>` [modifying the map object](https://github.com/VictorCazanave/vue-svg-map#modify-a-map) (I forgot about this feature 😅).
I tried make the documentation a bit more clear, but feel free to share your feedback if it's not or if it doesn't solve your issue.
