### ISSUE TITLE
How to add State names or codes

### ISSUE THREAD

**Issue by avpuchkova** [VictorCazanave/vue-svg-map#53]
Is it possible to show  State Names or Codes on usa.svg? I know I should use slot and text, but could you give an example, please?

**Comment by VictorCazanave** [comment]
Here is [quick example](https://codesandbox.io/s/vue-svg-map-with-labels-nym4eg?file=/src/App.vue) with few state codes. Of course, you can customize the labels with CSS and other SVG tags (like `<circle>`, `<rect>`...). 
Hope it can help (not too late 😅)
