### ISSUE TITLE
Nuxt (Unexpected token 'export')

### ISSUE THREAD

**Issue by zernonia** [VictorCazanave/vue-svg-map#7]
I'm not sure what's wrong.. I've follow all the instructions for a simple map. But this error pops out instead. 

Thank you replying

**Comment by VictorCazanave** [comment]
Hi @zernonia ,
Do you use Server-Side Rendering?

**Comment by VictorCazanave** [comment]
@zernonia Did you solve your issue?
I've never used SSR, then if the component is broken or the documentation is complete, please let me know and I'll fix it.

**Comment by zernonia** [comment]
> @zernonia Did you solve your issue?
> I've never used SSR, then if the component is broken or the documentation is complete, please let me know and I'll fix it.

Hi, I'm able to solve the problem by simply copy the svgmap file (with the world map and etc) to another file, then import it into my project. 

I doubt that's the SSR problem, but I'm not too sure about the cause.

**Comment by VictorCazanave** [comment]
Hmm... okay 🤔

JFYI I followed [this documentation](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#SSR-Usage) to support SSR, so you may need to import the component like that: `import SvgMap from 'vue-svg-map/sfc/svg-map'`

**Comment by bennyzen** [comment]
I'm facing a similar issue when using Nuxt with `target: 'static'`. Just can't get it to work. Maybe someone has a hint.

**Comment by MLousdal** [comment]
I was having the same problem when using `target: static`. I found that the problem is because Nuxt expects a CommonJS module, but the module from 'svg-maps' is an ES6. To solve it I added a transpile rule to build in `nuxt.config.js`.

```
  build: {
    transpile: [
      '@svg-maps/denmark',
    ]
  },
```
