### ISSUE TITLE
export TooltipHeatMap was not found in vue-svg-map

### ISSUE THREAD

**Issue by fitsumbelay** [VictorCazanave/vue-svg-map#9]
where is tooltip heat map 

am using vue-svg-map for showing heat map with tooltip but i cant find it

**Comment by VictorCazanave** [comment]
The tooltip heat map is not a component of vue-svg-map package, but just an example of how to use `SvgMap` component. The source code is [here](https://github.com/VictorCazanave/vue-svg-map/blob/master/demo/src/components/tooltip-heat-map.vue) and can probably be improved.
